# Lab01 - 21127333 - Nguyễn Việt Kim

# Self Assessment
| Task      | Percentage |
| --------  | ------- |
| Mean      | 100    |
| Median    | 100     |
| Max       | 80   |
| Min       | 80    |
| Range      | 0    |
| Variance    | 100    |
| Standard Deviation    | 100    |
| Covariance    | 100    |
| Correlation    | 0    |

# Import Numpy and other libraries

In [108]:
import numpy as np

# Given sample arr of vector X
X = np.random.randint(0, 10, size=(3, 4, 5))
Y = np.random.randint(0, 10, size=(3, 4, 5))
print(X)
print(Y)

[[[8 1 0 6 7]
  [6 7 5 7 7]
  [5 2 5 7 0]
  [9 7 8 6 9]]

 [[8 1 3 6 7]
  [8 7 4 0 8]
  [8 6 0 6 7]
  [6 3 0 4 0]]

 [[3 6 5 5 1]
  [5 3 7 3 7]
  [6 6 6 6 8]
  [9 9 1 1 4]]]
[[[6 7 3 2 8]
  [4 2 8 2 6]
  [4 9 8 0 8]
  [0 9 9 5 4]]

 [[0 4 6 4 2]
  [3 9 2 6 2]
  [5 4 9 2 5]
  [4 4 2 5 6]]

 [[0 5 9 9 8]
  [2 4 5 0 7]
  [7 7 1 2 1]
  [9 3 1 5 4]]]


Consider the `X` vector of data with `n` samples. Each samples has `p` data. The `X` vector is shown as below:
$$
    X = \begin{bmatrix}    
            x_{11} & x_{12} & ... & x_{1p}\\
            x_{21} & x_{22} & ... & x_{2p}\\
            ... & ... & ... & ...\\
            x_{j1} & x_{j2} & ... & x_{jp}\\
            ... & ... & ... & ...\\
            x_{n1} & x_{n2} & ... & x_{np}
        \end{bmatrix}
$$

# Mean of a data set

The median of a data set is calculate by the following formula:
$$
   \overline{x_{k}} = \frac{1}{n} \sum_{j=1}^nx_{jk}, k=1,2,...,p
$$
In the implementation of the median formula, the mean function take in the parameters of the data set and the axis of the function where the median is calculated.

By default, the `axis` is set to `None`, which means that when the axis is not defined, the mean function flatten the array and calculate the mean of that array. If the axis is defined, the mean function calculate the mean by the axis and return the numpy array of the mean vectors.

Pseudo code for the function:
```
BEGIN
    IF axis = None:
        arr = arr.flatten()
        return sum(arr) / len(arr)
    IF axis = 0:
        total_sum = [0] * len(arr[0])
        count = [0] * len(arr[0])
        FOR EACH sub_array IN arr:
            Mean of each sub_array
        RETURN mean
    ELSE IF axis >= 1:
        FOR sub_arr in arr:
            // Recursive for calculating each mean vector
            mean.append(Mean(sub_arr, axis - 1))
        RETURN mean
    ELSE
        Raise Error
END
```

In [2]:
def Mean(arr, axis=None):
    if axis == None:
        flat_arr = arr.flatten()
        return sum(flat_arr) / len(flat_arr)
    if axis == 0:
        # Calculate mean along axis 0 (columns)
        total_sum = [0] * len(arr[0])
        count = [0] * len(arr[0])
        for sub_array in arr:
            for i, value in enumerate(sub_array):
                total_sum[i] += value
                count[i] += 1
        return np.array([sum_ / cnt for sum_, cnt in zip(total_sum, count)])
    elif axis >= 1:
        # Calculate mean along axis 1 (rows)
        return np.array([Mean(sub_array, axis=axis - 1) for sub_array in arr])
    else:
        # Handle other axes
        raise Exception("The axis is out of range")


In [3]:
print(np.mean(X))
print(Mean(X))
print("----------------------------------------------------------------")

print(np.mean(X, axis=0))
print(Mean(X, axis=0))
print("----------------------------------------------------------------")

print(np.mean(X, axis=1))
print(Mean(X, axis=1))

4.7
4.7
----------------------------------------------------------------
[[3.         5.         6.66666667 5.33333333 6.        ]
 [1.33333333 3.         4.33333333 5.33333333 4.        ]
 [4.66666667 5.33333333 6.66666667 7.66666667 4.66666667]
 [5.66666667 4.33333333 4.66666667 1.66666667 4.66666667]]
[[3.         5.         6.66666667 5.33333333 6.        ]
 [1.33333333 3.         4.33333333 5.33333333 4.        ]
 [4.66666667 5.33333333 6.66666667 7.66666667 4.66666667]
 [5.66666667 4.33333333 4.66666667 1.66666667 4.66666667]]
----------------------------------------------------------------
[[4.25 6.25 6.5  5.   3.5 ]
 [1.25 3.25 4.5  3.   5.75]
 [5.5  3.75 5.75 7.   5.25]]
[[4.25 6.25 6.5  5.   3.5 ]
 [1.25 3.25 4.5  3.   5.75]
 [5.5  3.75 5.75 7.   5.25]]


# Median of a data set

The function checks if the input data is a NumPy array and convert the array to NumPy array. The function then compute the median of the vector by the following formula:
$$  
f(a,b) = 
     \begin{cases}
       m = \text{sorted\_arr}[\frac{n}{2}] & \text{if n is odd}\\
       m = \frac{\text{sorted\_arr}[\frac{n}{2} - 1] + \text{sorted\_arr}[\frac{n}{2}]}{2} & \text{if n is even} \\
     \end{cases}
$$
Where `n` is the number of flattened array if the `axis` is `None`, or the number of vector along the `axis` otherwise.
- If `axis` is `None`, the function computes the median of the flattened array by sorting the data and finding the middle value(s).
- If `axis` is specified, the function computes the median along the specified axis by sorting the data along that axis and finding the middle value(s) for each slice along the axis.

The function returns the computed median value(s) based on the specified axis or across all axes if `axis` is `None`.

Pseudo code for the function:

```
BEGIN:
    IF axis = None:
        
    IF axis == 0:
        median_values = []
        FOR i FROM 0 TO (length of the first row of arr - 1):
            // Sort the array
            column_values = sort([element at index i in each row for row in arr])
            column_len = length of column_values
            // Get the median value
            IF column_len is even:
                median_values.append((column_values[column_len // 2 - 1] + column_values[column_len // 2]) / 2)
            ELSE:
                median_values.append(column_values[column_len // 2])
        RETURN an array of median_values
    ELSE IF axis >= 1:
        median_values = []
        FOR EACH sub_array IN arr:
            // Recursive to calculate the median along axis
            median_values.append(Median(sub_array, axis=axis - 1)) 
        RETURN median_values
    ELSE:
        # Handle other axes
        RAISE ValueError("The axis is out of range")
END
```

In [4]:
def Median(arr, axis=None):
    if axis is None:
        flat_arr = arr.flatten()
        flat_arr.sort()
        n = len(flat_arr)
        if n % 2 == 1:
            median = flat_arr[n // 2]
        else:
            median = (flat_arr[n // 2 - 1] + flat_arr[n // 2]) / 2
        return median

    if axis == 0:
        # Calculate median along axis 0 (columns)
        median_values = []
        for i in range(arr.shape[1]):
            column_values = np.sort(arr[:, i])
            column_len = len(column_values)
            if column_len % 2 == 0:
                median_values.append((column_values[column_len // 2 - 1] + column_values[column_len // 2]) / 2)
            else:
                median_values.append(column_values[column_len // 2])
        return np.array(median_values)

    elif axis >= 1:
        # Calculate median along axis 1 (rows)
        return np.array([Median(sub_array, axis=axis - 1) for sub_array in arr])

    else:
        # Handle other axes
        raise ValueError("The axis is out of range")


In [5]:
print(np.median(X))
print(Median(X))
print("----------------------------------------------------------------")

print(np.median(X, axis=0))
print(Median(X, axis=0))
print("----------------------------------------------------------------")

print(np.median(X, axis=1))
print(Median(X, axis=1))

5.0
5.0
----------------------------------------------------------------
[[3. 3. 7. 5. 6.]
 [1. 2. 3. 7. 5.]
 [5. 6. 8. 7. 3.]
 [7. 5. 5. 2. 6.]]
[[3 3 5 7 8]
 [0 0 1 2 3]
 [0 4 6 7 9]
 [0 1 2 4 6]]
----------------------------------------------------------------
[[4.  7.  6.5 4.5 3.5]
 [1.  2.5 4.  2.5 7. ]
 [5.  4.  6.  8.  5.5]]
[[4.  7.  6.5 4.5 3.5]
 [1.  2.5 4.  2.5 7. ]
 [5.  4.  6.  8.  5.5]]


# Max of the data set
```
BEGIN
    IF axis = None:
        arr = arr.flatten()
        arr.sort()
        RETURN arr[len(arr) - 1]
    
    IF axis = 0:
        max_values = []
        FOR i = 0 TO length(arr[0]):
            column_values = Sort(arr[:, i])
            max_values.append(Max(column_values))
        RETURN max_values
    
    ELSE IF axis >= 1:
        max_values = []
        FOR EACH sub_array IN arr:
            max_values.append(Max(sub_array, axis - 1))
        RETURN max_values
    
    ELSE
        Raise ValueError("The axis is out of range")
END
```

In [97]:
def Max(arr, axis=None):
    if axis is None:
        flat_arr = arr.flatten()
        flat_arr.sort()
        return flat_arr[len(flat_arr) - 1]

    if axis == 0:
        # Calculate max along axis 0 (columns)
        max_values = []
        for i in range(arr.shape[1]):
            column_values = np.sort(arr[:, i])
            max_values.append(Max(column_values))  # Append the minimum value of the column
        return np.array(max_values)

    elif axis >= 1:
        # Calculate minimum along axis 1 (rows) or higher dimensions recursively
        return np.array([Max(sub_array, axis=axis - 1) for sub_array in arr])

    else:
        # Handle other axes
        raise ValueError("The axis is out of range")


In [99]:
print(Max(X))
print(np.max(X))
print("----------------------------------------------------------------")

print(Max(X, axis=0))
print(np.max(X, axis=0))
print("----------------------------------------------------------------")

print(Max(X, axis=1))
print(np.max(X, axis=1))


9
9
----------------------------------------------------------------
[9 9 9 9]
[[5 9 7 9 8]
 [3 5 7 9 7]
 [9 8 8 9 9]
 [9 6 5 3 8]]
----------------------------------------------------------------
[[9 9 8 9 7]
 [3 6 7 7 9]
 [9 5 8 9 8]]
[[9 9 8 9 7]
 [3 6 7 7 9]
 [9 5 8 9 8]]


# Min of the data set
```
BEGIN
    IF axis = None:
        arr = arr.flatten()
        arr.sort()
        RETURN arr[0]

    IF axis = 0:
        min_values = []
        FOR i = 0 TO length(arr[0]):
            column_values = Sort(arr[:, i])
            min_values.append(Min(column_values))
        RETURN min_values

    ELSE IF axis >= 1:
        min_values = []
        FOR EACH sub_array IN arr:
            min_values.append(Min(sub_array, axis - 1))
        RETURN min_values

    ELSE
        Raise ValueError("The axis is out of range")
END
```

In [96]:
def Min(arr, axis=None):
    if axis is None:
        flat_arr = arr.flatten()
        flat_arr.sort()
        return flat_arr[0]

    if axis == 0:
        # Calculate minimum along axis 0 (columns)
        min_values = []
        for i in range(arr.shape[1]):
            column_values = np.sort(arr[:, i])
            min_values.append(Min(column_values))  # Append the minimum value of the column
        return np.array(min_values)

    elif axis >= 1:
        # Calculate minimum along axis 1 (rows) or higher dimensions recursively
        return np.array([Min(sub_array, axis=axis - 1) for sub_array in arr])

    else:
        # Handle other axes
        raise ValueError("The axis is out of range")


In [94]:
print(Min(X))
print(np.min(X))
print("----------------------------------------------------------------")

print(Min(X, axis=0))
print(np.min(X, axis=0))
print("----------------------------------------------------------------")

print(Min(X, axis=1))
print(np.min(X, axis=1))

0
0
----------------------------------------------------------------
[1 0 0 0]
[[1 3 6 2 4]
 [0 2 3 0 0]
 [0 2 4 7 2]
 [1 2 4 0 0]]
----------------------------------------------------------------
[[0 2 5 2 0]
 [0 2 3 0 0]
 [3 2 3 3 2]]
[[0 2 5 2 0]
 [0 2 3 0 0]
 [3 2 3 3 2]]


# Range of the sample

In [ ]:
def range(data, axis=None):
    # If axis is None, compute the PTP of the flattened array
    if axis is None:
        data_flat = [value for sublist in data for value in sublist]
        return max(data_flat) - min(data_flat)
    
    # If axis is specified, compute the PTP along the specified axis
    if isinstance(axis, int):
        axes = (axis,)
    else:
        axes = axis
    
    if any(ax < 0 for ax in axes):
        axes = tuple(ax + len(data[0]) for ax in axes)
    
    if any(ax >= len(data[0]) for ax in axes):
        raise ValueError("Axis value is out of range")
    
    result = data
    for ax in sorted(axes):
        result = [row[ax] for row in result]
    
    min_val = min(result)
    max_val = max(result)
    
    return max_val - min_val

In [ ]:
# print(range(X))
print(np.ptp(X))

# Variance and the standard deviation of the sample

Given the mean vector of the `X`, from that, we can calculate the variance of the sample by this formula:
$$
    S_{k}^2 = S_{kk} = \frac{1}{n}\sum_{j=1}^n(x_{jk} - \overline{x_{k}})^2, k=1,2,...,p
$$

Where the standard deviation of the sample is the square root of the variance

In [105]:
def Variance(data, axis=None):
    # Calculate the mean along the specified axis with keepdims=True
    mean_vector = Mean(data, axis=axis)

    # Calculate the squared deviations
    squared_deviations = (data - mean_vector) ** 2

    # Calculate the variance along the specified axis
    variance_vector = Mean(squared_deviations, axis=axis)

    return variance_vector

def Standard_deviation(data, axis=None):
    return np.sqrt(Variance(data, axis=axis))

The function first calculate the mean of the data set. The function then calculate the square of the deviation $(x_{jk} - \overline{x_k})^2$ where $k=1,2,...,p$. The final result is the mean of the squared deviations.

In [106]:
print(np.var(X))
print(Variance(X))

print(Standard_deviation(X))

8.076666666666664
8.076666666666664
2.8419476889391655


# Covariance of the sample

The provided code defines a Python function `covariance(data)` that calculates the covariance matrix of a given dataset.
The covariance between two features $ X_i $ and $ X_k $ is calculated using the formula:

$$ 
   \text{cov}(X_i, X_k) = \frac{1}{n} \sum_{j=1}^{n} (X_{ij} - \bar{X_i}) \cdot (X_{kj} - \bar{X_k}) 
$$

Where:
   - $ X_i $ and $ X_k $ are the values of feature `i` and feature `k` respectively.
   - $ \bar{X_i} $ and $ \bar{X_k} $ are the mean values of feature `i` and feature `k` respectively.
   - $ n $ is the number of observations.

In [101]:
def Covariance(data):
    n = data.shape[0]
    p = data.shape[1]
    
    # Compute means along each feature (column)
    means = Mean(data, axis=0)

    cov_matrix = np.zeros((p, p))
    
    # Compute covariance for each pair of features
    for i in range(p):
        for k in range(p):
            diff_i = data[:, i] - means[i]
            diff_k = data[:, k] - means[k]
            cov_matrix[i, k] = np.sum(diff_i * diff_k) / n
    
    return cov_matrix

In [104]:
print(Covariance(X))

[[ 21.77777778  -2.33333333   4.          10.        ]
 [ -2.33333333  30.66666667 -10.           2.33333333]
 [  4.         -10.          33.77777778  12.44444444]
 [ 10.           2.33333333  12.44444444  27.77777778]]
